### ISSUE TITLE
geom_density_ridges not computing density correctly?

### ISSUE THREAD

**Issue by dylanjm** [wilkelab/ggridges#13]
Hi, 

I'm working with the `nycflights13::flights` data set and attempting to use `geom_density_ridges()` to show departure delay between the three airports.  I am using version 0.4.1 and R 3.4.3. 

Here is my code using ggridges:

```
flights %>%
  group_by(origin) %>% 
  filter(sched_dep_time < 1200, origin %in% c("JFK", "LGA", "EWR")) %>%
  na.omit() %>%
  ggplot(aes(x = dep_delay, y = origin)) + 
  geom_density_ridges() + 
  coord_cartesian(xlim = c(-20,20))
```

![rplot](https://user-images.githubusercontent.com/15963026/35475001-1fc1dc88-0354-11e8-9b33-3daa5797885a.png)

I thought it was a little weird that EWR and JFK seem to have really similar distributions so I did another density plot just using ggplot:

```
flights %>%
  group_by(origin) %>% 
  filter(sched_dep_time < 1200, origin %in% c("JFK", "LGA", "EWR")) %>%
  na.omit() %>%
  ggplot(aes(x = dep_delay, fill = origin)) + 
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(-20,20))
```

![rplot01](https://user-images.githubusercontent.com/15963026/35475011-4f5ed536-0354-11e8-95d9-29740e718ef7.png)

Here we can clearly see the densities are different, yet the ggridges plot shows them to be the same.  Am I doing something wrong with my code or is there a larger issue at hand?

Thanks,

**Comment by clauswilke** [comment]
You could always calculate the densities with `stat_density()` if you prefer that:
```r
flights %>%
  group_by(origin) %>% 
  filter(sched_dep_time < 1200, origin %in% c("JFK", "LGA", "EWR")) %>%
  na.omit() %>%
  ggplot(aes(x = dep_delay, y = origin, height = ..density..)) + 
  geom_density_ridges(stat = "density") + 
  coord_cartesian(xlim = c(-20,20))
```
<img width="503" alt="screen shot 2018-01-27 at 1 17 58 pm" src="https://user-images.githubusercontent.com/4210929/35475465-96edf958-0364-11e8-91e5-daafb7839dad.png">

The key reason why your figures look the way they do, though, is because you're calculating densities over a huge range of x values and then zoom into a small snippet of that. I think you should first limit the data to your range of interest and then calculate the densities. The discrete, straight lines in both of your figures are the telltale sign that something is going wrong in your density estimations.

**Comment by dylanjm** [comment]
Ahh I see thank you!
